language: objective-c
os: osx
osx_image: xcode7.3

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

env:
    global:
        - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=1

script:
    - set -o pipefail
    - xcodebuild clean test -project C4iOS.xcodeproj -scheme C4 -sdk iphonesimulator | xcpretty
